import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS udemy</title>
        <meta name="descrption" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <h1 className="text-3xl font-bold underline">こんにちわ</h1>
    </>
  );
}
