import Head from 'next/head';
import Image from 'next/image';
import TimeLine from './components/TimeLine';

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS udemy</title>
        <meta name="descrption" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <TimeLine />
    </>
  );
}
